site_name: ZigDevWiki
site_url: https://zigdevwiki.github.io
repo_url: https://github.com/ZigDevWiki/zigdevwiki.github.io
edit_uri: 'edit/main/docs/'
theme:
  name: material
  favicon: assets/logo.ico
  logo: assets/logo.png
  palette:
      scheme: slate
      primary: orange
      accent: deep orange
  features:
    - navigation.instant
    - toc.integrate
markdown_extensions:
  - meta

extra:
  social:
    - icon: fontawesome/brands/telegram
      link: https://t.me/xyzroe
      name: '@xyzroe'
  analytics:
    provider: google
    property: UA-203059197-2
plugins:
  - search:
      lang:
        - en
        - ru
